### ISSUE TITLE
Please upload the latest version to CTAN

### ISSUE THREAD

**Issue by Josef-Friedrich** [uliska/lilyglyphs#102]
Please upload the latest version to CTAN

06aa0a6db6b1710f3a276fd36ffe2bd6688087b0 fixed an annoying bug (whitespace after the glyphs or ugly rectangles after the glyph)

I have tested 06aa0a6db6b1710f3a276fd36ffe2bd6688087b0 and this version is ok.

**Comment by uliska** [comment]
Thank you for the friendly reminder.
However, I'll try to find the time to fix #101 first because that one is actively blocking the package to be included in TeX Live on multiple platforms.

**Comment by Josef-Friedrich** [comment]
I understand. Thank you for your quick response.

**Comment by uliska** [comment]
I'll look into #103. Maybe we have the solution easily available.

Am 23. September 2020 09:09:43 MESZ schrieb Josef Friedrich <notifications@github.com>:
>I understand. Thank you for your quick response.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/uliska/lilyglyphs/issues/102#issuecomment-697178247

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
Should ba fixed by #103

**Comment by Josef-Friedrich** [comment]
Thank you very much! At the moment only the old version 0.2.3 is available on CTAN

**Comment by uliska** [comment]
It will be available within 24 hours

**Comment by Josef-Friedrich** [comment]
Thank you for this update. I have tested it. It works great!
