### ISSUE TITLE
kernel/key-unknown

### ISSUE THREAD

**Issue by chbuschmann** [uliska/lilyglyphs#90]
I get the following error when compiling with TexPad:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
./Masterthesis.tex:41: LaTeX error: "kernel/key-unknown"
! 
! The key 'piano/wfont' is unknown and is being ignored.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

![skjermbilde 2016-05-22 kl 10 33 11](https://cloud.githubusercontent.com/assets/9821670/15453121/f5bd8f16-2008-11e6-874b-b34316e91fa2.png)

**Comment by uliska** [comment]
I think this is not related to lilyglyphs but you have to remove the extra "w" at the end of l.38.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by chbuschmann** [comment]
I've had that error there for weeks, and *boom* a renegade "w" hits you. Feel free to remove this non-issue.

**Comment by uliska** [comment]
You could have asked weeks ago ;-(

**Comment by uliska** [comment]
Oops I meant ;-)

**Comment by chbuschmann** [comment]
Hah! 👍
