### ISSUE TITLE
Missing character: There is no " (U+0022) in font [emmentaler-16.otf]

### ISSUE THREAD

**Issue by LolitaZT** [uliska/lilyglyphs#93]
In [genericAccess.inp](https://github.com/uliska/lilyglyphs/blob/master/core/genericAccess.inp#L130) line 130:
``` lua 
(stringformat ([[\char"%X"]], chr))
```
there is invalid double quote (") right after an argument. It causes the following message to appear in compilation *.log file:
"Missing character: There is no " (U+0022) in font [emmentaler-16.otf]"

Minimal working example:
```latex
\documentclass{article}
\usepackage{fontspec}
\RequirePackage{lilyglyphs}

\begin{document}
\crotchetRest
\end{document}
```
Compiled with TeXLive 2016, LuaTeX 1.0.0

**Comment by uliska** [comment]
Don't know when this was fixed but the " isn't there anymore

**Comment by Pinimo** [comment]
Hi Urs @uliska , this bug seems to be in the current CTAN distro: http://ctan.tetaneutral.net/macros/luatex/latex/lilyglyphs/tex/core/ .

I fixed it temporarily in my Docker image with:
`sed -i '130s/char"%X"/char"%X/' /home/thesis/texlive/texmf-dist/tex/lualatex/lilyglyphs/core/genericAccess.inp`
